<?php

namespace Test;

use PHPUnit\Framework\TestCase;

class TemperTest extends TestCase
{



    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        require_once dirname(__DIR__) . '/vendor/autoload.php';
       // Load bootstrap file
//        require "../bootsrap.php";

//        $BASE_URL = $_SERVER['SERVER_NAME'];


    }
}