<?php

namespace Test;

use PHPUnit\Framework\TestCase;

class TemperTest extends TestCase
{



    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        require_once dirname(__DIR__) . '/vendor/autoload.php';
        $containerBuilder = new \DI\ContainerBuilder();
        $containerBuilder->useAutowiring(true);
        $containerBuilder->useAnnotations(false);
        $this->container = $containerBuilder->build();

        $containerBuilder = new \DI\ContainerBuilder();
        $containerBuilder->useAutowiring(true);
        $containerBuilder->useAnnotations(false);
        $this->container = $containerBuilder->build();
    }
}